In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
df = pd.read_csv(r'xf-n2415-il-200000.csv', header=9)

In [7]:
df

     Alpha      Cl       Cd      Cdp      Cm  Top_Xtr  Bot_Xtr
0   -14.25 -0.7841  0.07840  0.07388 -0.0595   1.0000   0.0563
1   -14.00 -0.8778  0.06085  0.05586 -0.0730   1.0000   0.0548
2   -13.75 -0.9147  0.05409  0.04880 -0.0764   1.0000   0.0547
3   -13.50 -0.9374  0.04984  0.04432 -0.0769   1.0000   0.0549
4   -13.25 -0.9551  0.04665  0.04090 -0.0758   1.0000   0.0553
..     ...     ...      ...      ...     ...      ...      ...
130  18.25  1.3168  0.09228  0.08633  0.0050   0.0493   1.0000
131  18.50  1.2992  0.09830  0.09260  0.0023   0.0488   1.0000
132  18.75  1.2802  0.10481  0.09935 -0.0008   0.0483   1.0000
133  19.00  1.2592  0.11193  0.10670 -0.0045   0.0479   1.0000
134  19.25  1.2332  0.12028  0.11530 -0.0093   0.0476   1.0000

[135 rows x 7 columns]