In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('2024A MEAM543 UAV Database  - Sheet1.csv', skiprows=1)
df.columns = [col.replace('/','').strip()
              .replace('\n', '_').replace(' ','_')
              .replace('[','').replace(']','')
               .replace('(','').replace(')','').replace("\"","") for col in df.columns.to_list()]
df

,Aircraft_Name,Last_Name_of_Person_Posting,Link,Cost_$,Mission_Description,Mission_Equipment,Maximum_Takeoff_Weight_lb,Empty_Weight_lb,Max_Payload_Weight_lb,Max_Fuel__Battery_Weight_lb,...,Takeoff__Recovery_Type,Required_Runway_Distance_feet,Max_Speed_kts,Cruise_Speed_kts,Stall_Speed_kts,Service_Ceiling_ft,Cruise_Altitude_ft,Wing_Area_ft^2,Span__ft,Length_feet
0,Trinity F90\n(Unlocked),Kothmann,https://www.quantum-systems.com/project/trinit...,"$16,900",Agricultural Survey,High-precision position measurement when combi...,11,NaN,1.54,NaN,...,VTOL (Props rotate to vertical position),0,NaN,33,NaN,NaN,0,3.3,7.48,NaN
1,Penguin C,Kothmann,https://edgeautonomy.io/solutions/penguin-c/\n...,"$433,000",NaN,NaN,49.6,22,20,NaN,...,Catapult\nParachute,0,62.2,40,25.3,16000,5000,8.5,10.83,7.5
2,RQ-12A Wasp IV,Zaccaria,https://www.navair.navy.mil/product/Group-1-Sm...,"$22 million for a package, not specified how many",NaN,EO/IR gimbaled cameras,2.85,0.95,NaN,NaN,...,"hand launched, stall dad stick landing",NaN,35,22-35,NaN,10000,500,NaN,3.3,2.7
3,MQ-4CTriton,Zaccaria,https://www.navair.navy.mil/product/MQ-4C http...,$123-180 million,Persistent Maritime ISR,unique and robust mission sensor suite that pr...,"32,250 pounds",14945,3200 (internal)\n2400 (external),NaN,...,Fully autonomous takeoff/landing with crew of ...,NaN,320,NaN,NaN,56000,NaN,NaN,130.9,47.6
4,Insitu Inc. Scaneagle,Zaccaria,https://www.navair.navy.mil/product/Close-Rang...,$3.2 million,"ISR (intelligence, survelliance and reconnaiss...",stabilized electro-optical and/or infrared cam...,58,30.90â€“39.68,11,NaN,...,"superwedge launcher, skyhook retrival",NaN,80,50-60,NaN,NaN,NaN,NaN,10,4.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
252,RQ-11 Raven,Aditya,https://en.wikipedia.org/wiki/AeroVironment_RQ...,"$35,000",Low-Altitude Intelligence and Surveillance Mis...,EO/IR Camera,4.8,NaN,NaN,NaN,...,Hand-Launched; Autonomous Recovery,NaN,44,17,NaN,"14,000",NaN,NaN,4.5,3
253,IAI Heron (Machatz-1),Aditya,https://en.wikipedia.org/wiki/IAI_Heron,40 million,Strategic reconnaissance and surveillance oper...,"EO and IR sensors, thermal surveillance equipm...","2,535",617.3,550,NaN,...,Fixed tricycle landing gear,NaN,113,NaN,NaN,"30,000",NaN,NaN,54.5,27.9
254,General Atomics MQ-20 Avenger,Aditya,https://en.wikipedia.org/wiki/General_Atomics_...,$100 million,"Intelligence collection, precision penetration...","weather radar, TCAS (Traffic Collision Avoidan...",18200,11700,6500,7900,...,NaN,NaN,400,350,NaN,50000,NaN,N/A,66,44
255,ATLAS C4EYE,VItale,https://en.wikipedia.org/wiki/Atlas_C4EYE,NaN,"Target detection, search-and-rescue, recon","Gyroscopic stabilisers and gimbal, laser illum...",5.29 lbs,NaN,NaN,NaN,...,Hand-launched,NaN,58.28,NaN,NaN,16404,NaN,NaN,5.08,2.69
256,NaN,Vitale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
import re
def get_numbers(x):
    num_float = re.findall(r'\d+\.\d+', str(x))
    dec_float = re.findall(r'\d+', str(x))
    comma_seperated_dec = re.findall(r'\d+\,\d+', str(x))
    comma_seperated_float = re.findall(r'\d+\,\d+\.\d+', str(x))
    if num_float:
        return np.array([float(num) for num in num_float]).max()
    elif dec_float:
        return np.array([float(num) for num in dec_float]).max()
    elif comma_seperated_dec:
        return np.array([float(num.replace(',','')) for num in comma_seperated_dec]).max()
    elif comma_seperated_float:
        return np.array([float(num.replace(',','')) for num in comma_seperated_float]).max()
    else:
        return np.nan

In [4]:
df.Max_Payload_Weight_lb = df.Max_Payload_Weight_lb.apply(get_numbers)
df.Max_Flight_Distance_Range_miles = df.Max_Flight_Distance_Range_miles.apply(get_numbers)
df.Cruise_Altitude_ft = df.Cruise_Altitude_ft.apply(get_numbers)
Payload_mask = (df.Max_Payload_Weight_lb > (3.3*0.75)) & (df.Max_Payload_Weight_lb < (3.3*1.25))
Range_mask = (df.Max_Flight_Distance_Range_miles > (30*0.55)) & (df.Max_Flight_Distance_Range_miles < (30*1.25))
df[Payload_mask & Range_mask]

,Aircraft_Name,Last_Name_of_Person_Posting,Link,Cost_$,Mission_Description,Mission_Equipment,Maximum_Takeoff_Weight_lb,Empty_Weight_lb,Max_Payload_Weight_lb,Max_Fuel__Battery_Weight_lb,...,Takeoff__Recovery_Type,Required_Runway_Distance_feet,Max_Speed_kts,Cruise_Speed_kts,Stall_Speed_kts,Service_Ceiling_ft,Cruise_Altitude_ft,Wing_Area_ft^2,Span__ft,Length_feet
99,Bluebird Aero Spylite,Hajjar,https://www.militaryfactory.com/aircraft/detai...,NaN,"Intelligence, reconnaissance",Cameras,20,15,4.0,NaN,...,Slingshot,NaN,65,NaN,NaN,"3,281",3.0,NaN,9,4

In [5]:
cruise_mask = (df.Cruise_Altitude_ft > 0.75*11483) & (df.Cruise_Altitude_ft < 1.25*11483)
df[cruise_mask]

,Aircraft_Name,Last_Name_of_Person_Posting,Link,Cost_$,Mission_Description,Mission_Equipment,Maximum_Takeoff_Weight_lb,Empty_Weight_lb,Max_Payload_Weight_lb,Max_Fuel__Battery_Weight_lb,...,Takeoff__Recovery_Type,Required_Runway_Distance_feet,Max_Speed_kts,Cruise_Speed_kts,Stall_Speed_kts,Service_Ceiling_ft,Cruise_Altitude_ft,Wing_Area_ft^2,Span__ft,Length_feet
77,STM Kargu,Mann,https://www.stm.com.tr/uploads/docs/1689676408...,NaN,"asymmetric warfare, counter insurgency","explosives, facial recognition system",15.56,NaN,33.9500,NaN,...,vertical takeoff / landing,NaN,39,39,NaN,NaN,9842.52,NaN,1.52,2.32
159,ShadowÂ®-200 FQ-7B,Cheng,https://irp.fas.org/program/collect/uas-army.pdf,NaN,Provide Army Brigade Commanders with tactical ...,Laser Designator,462,380,60.0000,NaN,...,Conventional,NaN,150,NaN,NaN,NaN,14000.00,NaN,14,NaN
194,CASC Rainbow CH-1,Lele Yang,https://en.wikipedia.org/wiki/CASC_Rainbow,NaN,reconnaissance and surveillance missions,NaN,NaN,88.1849,9.9208,57.3202,...,parachute,NaN,66.9546,80.9935,NaN,15091,9842.52,NaN,14.4357,12.30315
218,MAKEFLYEASY HERO 2180MM UAV VTOL,Wang,https://www.uavmodel.com/products/makeflyeasy-...,"$1,499",Lightweight mapping drone,"Flying platform, Power system,",15.4,14.3,2.2000,NaN,...,Vertical takeoff and landing,NaN,250,NaN,NaN,NaN,9842.50,NaN,31,22

In [6]:
df.Max_Flight_Distance_Range_miles

0        62.00
1        60.00
2         3.10
3      9400.00
4          NaN
        ...
252       6.21
253     217.48
254    1800.00
255       9.32
256        NaN
Name: Max_Flight_Distance_Range_miles, Length: 257, dtype: float64

In [7]:
l = ((6.08-3.68)**2+(5.27-3.6)**2)**0.5

In [8]:
l*2.28/3

2.2221261530345204

In [9]:
2.28/13

0.17538461538461536